services:
  api:
    image: kv-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data
